openapi: 3.0.1
security:
  - OAuth2Auth: []

info:
  license:
    name: European Union Public License (EUPL) 1.2
    url: https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf
  contact:
    name: Simpl Programme
    email: cnect-simpl@ec.europa.eu
    url: https://simpl-programme.ec.europa.eu/
  title: Query Mapper Adapter API
  description: This the API  for the adapter to the Simpl Federated Catalogue located in the Governance authority node.
  version: 1.0.0
servers:
  - url: https://adapter.dev.simpl-europe.eu/v1
    description: Generated server url
paths:
  /selfDescriptions:
    get:
      tags:
        - Resource description search
      summary: Search the Federated Catalogue for Resource descriptions that contain the provided keyword. 
               Resource descriptions with access policy values other than the one defined in the Client access token will not be listed
      parameters:
        - name: searchString
          in: query
          required: true
          schema:
            type: string
          description: String value against which the search will be conducted.
          examples:
            returnValidResponse:
              value: asset03
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (1-based). Must be greater than 0.
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
          description: Number of items per page. Must be greater than 0.
        - name: User-Attributes
          in: header
          required: false
          schema:
            type: string
          description: Optional user attributes header
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchResponsePayload"
              examples:
                returnValidResponse:
                  value:
                    totalCount: 2
                    items:
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:InfrastructureOffering:a94ef06c-a12d-4308-89aa-fffcd8a61126"
                          offeringType: "infrastructure"
                          name: "text title for infrastructure resource."
                          inLanguage: "da"
                          description: "text description"
                          serviceAccessPoint: "http://serviceaccesspoint.com"
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:DataOffering:3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_235"
                          offeringType: "data"
                          name: "asset03"
                          description: "asset description"
                          inLanguage: "en"
                          serviceAccessPoint: "https://sd-ui.dev.simpl-europe.eu"
        '406':
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:notAcceptable
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/406
                title: Not Acceptable
                status: 406
                detail: Server cannot produce a response matching the list of acceptable values defined in the request's
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /selfDescriptions/advancedSearch:
    post:
      x-microcks-operation:
        dispatcher: SCRIPT
        dispatcherRules: |
          def jsonSlurper = new groovy.json.JsonSlurper()
          def requestBody = jsonSlurper.parseText(mockRequest.getRequestContent())
          def contractTemplateNode = requestBody?."simpl:ContractTemplate"
          def priceObject = requestBody?."simpl:OfferingPrice"?.price
          if (contractTemplateNode != null && contractTemplateNode.findAll().size() == 0) {
            return "returnBadRequestEmptyNodeDefinition"
          }
          if (priceObject != null && priceObject.customOperator != null) {
            return "returnBadRequestWrongPropertyNamesForPriceField"
          }
          return "returnValidResponse"
      tags:
        - Resource description search
      summary: Search the Federated Catalogue for Resource descriptions that match the provided search criteria in the request payload.
               Resource descriptions with access policy values other than the one defined in the Client access token will not be listed
      parameters:
        - name: User-Attributes
          in: header
          required: false
          schema:
            type: string
          description: Optional user attributes header
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/advancedSearchRequestPayload"
            examples:
              returnValidResponse:
                value:
                  simpl:OfferingPrice:
                    price:
                      op1: '>='
                      value1: '15'
                      op2: <
                      value2: '150'
                  simpl:GeneralServiceProperties:
                    name: asset002
                  simpl:ContractTemplate:
                    contractTemplateDocument: Contract Template 1234
              returnBadRequestEmptyNodeDefinition:
                value:
                  simpl:ContractTemplate: {}
              returnBadRequestWrongPropertyNamesForPriceField:
                value:
                  simpl:OfferingPrice:
                    price:
                      customOperator: '>='
                      value1: '15'
                      op2: <
                      value2: '150'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchResponsePayload"
              examples:
                returnValidResponse:
                  value:
                    totalCount: 2
                    items:
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:InfrastructureOffering:a94ef06c-a12d-4308-89aa-fffcd8a61126"
                          offeringType: "infrastructure"
                          name: "asset002"
                          inLanguage: "da"
                          description: "text description"
                          serviceAccessPoint: "http://serviceaccesspoint.com"
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:DataOffering:3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_235"
                          offeringType: "data"
                          name: "asset002"
                          description: "asset description"
                          inLanguage: "en"
                          serviceAccessPoint: "https://sd-ui.dev.simpl-europe.eu"

        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              examples:
                returnBadRequestEmptyNodeDefinition:
                  value:
                    type: urn:problem-type:simpl:badRequest
                    href: https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html
                    title: Bad Request
                    status: 400
                    detail: No Properties defined in simpl:ContractTemplate node. Please provide at least one property with searched value.
                    instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
                returnBadRequestWrongPropertyNamesForPriceField:
                  value:
                    type: urn:problem-type:simpl:badRequest
                    href: https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html
                    title: Bad Request
                    status: 400
                    detail: 'Wrong property names in node simpl:OfferingPrice. Allowed property names: op1, op2, value1, value2'
                    instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '406':
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:notAcceptable
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/406
                title: Not Acceptable
                status: 406
                detail: Server cannot produce a response matching the list of acceptable values defined in the request's
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '415':
          description: Unsupported Media Type
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:unsupportedMediaType
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/415
                title: Unsupported Media Type
                status: 415
                detail: Server refused to accept the request because the message content format is not supported.
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /participants/resourceDescriptions:
    get:
      tags:
        - Participant resource description
      summary: Return all resource descriptions with the participant id as defined in the Client access token.
      parameters:
        - name: orderBy
          in: query
          required: false
          schema:
            type: string
            enum: [publicationDate, resourceType]
            default: publicationDate
          description: Field to order the results by
        - name: User-Attributes
          in: header
          required: false
          schema:
            type: string
          description: Optional user attributes header
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchResponsePayload"
              examples:
                returnValidResponse:
                  value:
                    totalCount: 1
                    items:
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:InfrastructureOffering:a94ef06c-a12d-4308-89aa-fffcd8a61126"
                          offeringType: "infrastructure"
                          name: "text title for infrastructure resource."
                          inLanguage: "da"
                          description: "text description"
                          serviceAccessPoint: "http://serviceaccesspoint.com"
        '403':
          $ref: '#/components/responses/forbiddenErrorResponse'
        '406':
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:notAcceptable
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/406
                title: Not Acceptable
                status: 406
                detail: Server cannot produce a response matching the list of acceptable values defined in the request's
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /participants/resourceDescriptions/{resourceDescriptionId}:
    get:
      parameters:
        - name: resourceDescriptionId
          in: path
          description: 'value defined in credentialSubject.@id for given resource description'
          required: true
          schema:
            type: string
          examples:
            returnValidResponse:
              value: 3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_252
      tags:
        - Participant resource description
      summary: Return details of given resource description stored in federated catalogue
      responses:
        '200':
          $ref: '#/components/responses/getResourceDescriptionResponse'
        '403':
          $ref: '#/components/responses/forbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/notFoundErrorResponse'
        '406':
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:notAcceptable
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/406
                title: Not Acceptable
                status: 406
                detail: Server cannot produce a response matching the list of acceptable values defined in the request's
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    patch:
      tags:
        - Participant resource description
      summary: Revoke existing resource description. Endpoint will behave idempotently if resource description is already revoked.
      parameters:
        - name: resourceDescriptionId
          in: path
          required: true
          schema:
            type: string
            example: did:web:registry.gaia-x.eu:DataOffering:3mwO1pOqDQ_fID9jc9Az1TS5JKIS_eng_custom5
          description: 'value defined in credentialSubject.@id for given resource description'
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/notFoundErrorResponse'
        '403':
          $ref: '#/components/responses/forbiddenErrorResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /participants/resourceDescriptions/{resourceDescriptionId}/version:
    get:
      tags:
        - Participant resource description
      summary: Return list of resource descriptions with the same parent resource description id.
      parameters:
        - name: resourceDescriptionId
          in: path
          description: 'Parent resource description id.'
          required: true
          schema:
            type: string
          examples:
            validResourceDescriptionId:
              value: 3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_252
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (1-based). Must be greater than 0.
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
          description: Number of items per page. Must be greater than 0.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchResponsePayload"
              examples:
                returnValidResponse:
                  value:
                    totalCount: 2
                    items:
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:InfrastructureOffering:a94ef06c-a12d-4308-89aa-fffcd8a61126"
                          offeringType: "infrastructure"
                          name: "text title for infrastructure resource."
                          inLanguage: "da"
                          description: "text description"
                          serviceAccessPoint: "http://serviceaccesspoint.com"
                      - n:
                          claimsGraphUri:
                            - "did:web:registry.gaia-x.eu:DataOffering:3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_235"
                          offeringType: "infrastructure"
                          name: "asset03"
                          description: "asset description"
                          inLanguage: "en"
                          serviceAccessPoint: "https://sd-ui.dev.simpl-europe.eu"
        '401':
          $ref: '#/components/responses/unauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/forbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/notFoundErrorResponse'
        '406':
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: urn:problem-type:simpl:notAcceptable
                href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/406
                title: Not Acceptable
                status: 406
                detail: Server cannot produce a response matching the list of acceptable values defined in the request's
                instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  securitySchemes:
    OAuth2Auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read: Read access
            write: Write access
  schemas:
    Problem:
      description: |
        A Problem Details object (RFC 9457).

        Additional properties specific to the problem type may be present.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: An absolute URI that identifies the problem type
          default: about:blank  # kept for backwards-compatibility, type will be mandatory in problem-v2
        href:
          type: string
          format: uri
          description: An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
        title:
          type: string
          description: A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
      example:
        type: urn:problem-type:exampleOrganization:exampleProblem # "exampleOrganization" should be a short identifier for the organization that defines the problem type. "belgif" is used for problem types standardized in the Belgif REST guide
        href: "https://www.belgif.be/specification/rest/api-guide/#standardized-problem-types" # optional, should refer to documentation of the problem type, either of a belgif standardized or a custom problem type
        title: Description of the type of problem that occurred
        status: 400 # HTTP response status, appropriate for the problem type
        detail: Description of specific occurrence of the problem
        instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000

    searchResponsePayload:
      type: object
      properties:
        totalCount:
          type: integer
          example: 2
          description: Number of found Resource description.
        items:
          type: array
          items:
            type: string
          example:
            - n:
                claimsGraphUri:
                  - "did:web:registry.gaia-x.eu:InfrastructureOffering:a94ef06c-a12d-4308-89aa-fffcd8a61126"
                offeringType: "infrastructure"
                name: "text title for infrastructure resource."
                inLanguage: "da"
                description: "text description"
                serviceAccessPoint: "http://serviceaccesspoint.com"
            - n:
                claimsGraphUri:
                  - "did:web:registry.gaia-x.eu:DataOffering:3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_235"
                offeringType: "data"
                name: "asset 004"
                description: "asset description"
                inLanguage: "en"
                serviceAccessPoint: "https://sd-ui.dev.simpl-europe.eu"
          description: An array of general service properties nodes of a filtered out resource descriptions
        page:
          type: integer
          example: 1
          description: Current page number. Only present when totalCount > 100.
        pageSize:
          type: integer
          example: 20
          description: Number of items per page. Only present when totalCount > 100.
        total:
          type: integer
          example: 150
          description: Total number of items across all pages. Only present when totalCount > 100.
        totalPages:
          type: integer
          example: 8
          description: Total number of pages. Only present when totalCount > 100.
        next:
          type: string
          nullable: true
          example: "/selfDescriptions?searchString=test&page=2&pageSize=20"
          description: URL to the next page, or null if no next page available. Only present when totalCount > 100.

    advancedSearchRequestPayload:
      type: string
      description: Since resource descriptions as of now are schemaless the request body can be any JSON with proper structure.
                   Each JSON root key needs to correspond to a resource description node name. As a value for that key an JSON object need to be provided with the searched property names and values. In case of numerical values 
                   we can provide a range of searched values by providing op1 and op2 properties as described in the example.
      example:
        simpl:OfferingPrice:
          price:
            op1: '>='
            value1: '15'
            op2: <
            value2: '150'
        simpl:GeneralServiceProperties:
          name: asset002
        simpl:ContractTemplate:
          contractTemplateDocument: Contract Template 1234

  responses:
    internalServerErrorResponse:
      description: Internal Server error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: urn:problem-type:simpl:internalServerError
            href: https://www.belgif.be/specification/rest/api-guide/problems/internalServerError.html
            title: Internal Server Error
            status: 500
            detail: Internal Server Error
            instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
    notFoundErrorResponse:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: urn:problem-type:simpl:notFound
            href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/404
            title: Not Found
            status: 404
            detail: Resource with given id was not found.
            instance: urn:uuid:8795ff62-63f3-4474-912f-567f88ce2304
    forbiddenErrorResponse:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: urn:problem-type:simpl:forbidden
            href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/403
            title: Forbidden
            status: 403
            detail: Client is not authorized to access the requested resource.
            instance: urn:uuid:24a550c4-d7a8-4c06-91aa-35a80244776e
    unauthorizedErrorResponse:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: urn:problem-type:simpl:unauthorized
            href: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/401
            title: Invalid or expired token
            status: 401
            detail: Invalid or expired token
            instance: urn:uuid:24a550c4-d7a8-4c06-91aa-35a80244776e
    getResourceDescriptionResponse:
      description: Resource description details. Due to ever changing nature of resource description shape it is
        impossible to provide detailed description of each property.
      content:
        application/json:
          schema:
            type: string
          examples:
             returnValidResponse:
               value:
                 {
                   "@context": [
                     "https://www.w3.org/2018/credentials/v1",
                     "https://w3id.org/security/suites/jws-2020/v1"
                   ],
                   "credentialSubject": {
                     "@context": {
                       "gax-validation": "http://w3id.org/gaia-x/validation#",
                       "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                       "sh": "http://www.w3.org/ns/shacl#",
                       "simpl": "http://w3id.org/gaia-x/simpl#",
                       "skos": "http://www.w3.org/2004/02/skos/core#",
                       "xsd": "http://www.w3.org/2001/XMLSchema#"
                     },
                     "@id": "3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHF_TEST_252",
                     "rdf:type": {
                       "@id": "simpl:DataOffering"
                     },
                     "simpl:billingSchema": {
                       "rdf:type": {
                         "@id": "simpl:BillingSchema"
                       },
                       "simpl:billingSchemaDocument": "Billing Schema 1",
                       "simpl:billingSchemaHashAlg": "SHA-256",
                       "simpl:billingSchemaHashValue": "7cf87b4138c3d4ca015ba54ccc21c2e879a1eaa60e0979859484550aaa76bded",
                       "simpl:billingSchemaURL": "https://files.dev.simpl-europe.eu/static/pdf/BillingSchema1.pdf"
                     },
                     "simpl:contractTemplate": {
                       "rdf:type": {
                         "@id": "simpl:ContractTemplate"
                       },
                       "simpl:contractTemplateDocument": "Contract Template 1",
                       "simpl:contractTemplateHashAlg": "SHA-256",
                       "simpl:contractTemplateHashValue": "27883d9aec35ab16a3934e6581ed1b7f1b16feb75ead991c07ceff2e4a96fe58",
                       "simpl:contractTemplateURL": "https://files.dev.simpl-europe.eu/static/pdf/ContractTemplate1.pdf"
                     },
                     "simpl:dataProperties": {
                       "rdf:type": {
                         "@id": "simpl:DataProperties"
                       },
                       "simpl:format": "test"
                     },
                     "simpl:edcRegistration": {
                       "simpl:accessPolicyId": "12b5f80d-ec90-43bc-9d7c-ad1a2f5e0d7e",
                       "simpl:assetId": "2764f7d9-8044-407e-9eb4-d166c5d1eb85",
                       "simpl:contractDefinitionId": "ff23a62e-26f7-4a0d-b709-09c8ebe22cb2",
                       "simpl:servicePolicyId": "82c09c5c-eed9-4865-9a9f-6534cc84dd4a"
                     },
                     "simpl:generalServiceProperties": {
                       "rdf:type": {
                         "@id": "simpl:GeneralServiceProperties"
                       },
                       "simpl:description": "asset description",
                       "simpl:inLanguage": "en",
                       "simpl:name": "asset 004",
                       "simpl:offeringType": "data",
                       "simpl:serviceAccessPoint": {
                         "@type": "xsd:anyURI",
                         "@value": "https://sd-ui.dev.simpl-europe.eu"
                       }
                     },
                     "simpl:offeringPrice": {
                       "rdf:type": {
                         "@id": "simpl:OfferingPrice"
                       },
                       "simpl:currency": "EUR",
                       "simpl:license": {
                         "@type": "xsd:anyURI",
                         "@value": "https://sd-ui.dev.simpl-europe.eu"
                       },
                       "simpl:price": {
                         "@type": "xsd:decimal",
                         "@value": 10000
                       },
                       "simpl:priceType": "free"
                     },
                     "simpl:providerInformation": {
                       "rdf:type": {
                         "@id": "simpl:ProviderInformation"
                       },
                       "simpl:contact": "test@test.com",
                       "simpl:providedBy": "test",
                       "simpl:signature": "test"
                     },
                     "simpl:servicePolicy": {
                       "rdf:type": {
                         "@id": "simpl:ServicePolicy"
                       },
                       "simpl:access-policy": "{\"profile\":\"http://www.w3.org/ns/odrl/2/odrl.jsonld\",\"target\":\"3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHe\",\"assigner\":{\"uid\":\"provider\",\"role\":\"http://www.w3.org/ns/odrl/2/assigner\"},\"uid\":\"a5bedff0-e3e3-4806-8c83-9a97002fae4e\",\"@context\":\"http://www.w3.org/ns/odrl.jsonld\",\"@type\":\"Set\",\"permission\":[{\"target\":\"3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHe\",\"assignee\":{\"uid\":\"CONSUMER\",\"role\":\"http://www.w3.org/ns/odrl/2/assignee\"},\"action\":[\"http://simpl.eu/odrl/actions/search\"],\"constraint\":[]}]}",
                       "simpl:usage-policy": "{\"profile\":\"http://www.w3.org/ns/odrl/2/odrl.jsonld\",\"target\":\"3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHe\",\"assigner\":{\"uid\":\"provider\",\"role\":\"http://www.w3.org/ns/odrl/2/assigner\"},\"uid\":\"47b65a0c-d19d-4350-9225-13208ef649ff\",\"@context\":\"http://www.w3.org/ns/odrl.jsonld\",\"@type\":\"Set\",\"permission\":[{\"target\":\"3mwO1pOqDQ_fID9jc9Az1TS5JKIS_oinfKHe\",\"assignee\":{\"uid\":\"CONSUMER\",\"role\":\"http://www.w3.org/ns/odrl/2/assignee\"},\"action\":[\"http://www.w3.org/ns/odrl/2/use\"],\"constraint\":[{\"leftOperand\":\"http://www.w3.org/ns/odrl/2/deletion\",\"operator\":\"http://www.w3.org/ns/odrl/2/eq\",\"rightOperand\":\"after_use\"}]}]}"
                     },
                     "simpl:slaAgreements": {
                       "rdf:type": {
                         "@id": "simpl:SlaAgreements"
                       },
                       "simpl:slaAgreementsDocument": "Sla Agreements 1",
                       "simpl:slaAgreementsHashAlg": "SHA-256",
                       "simpl:slaAgreementsHashValue": "a75b83855522208dfb134f559447c8ca5864c6dc1d705c26f9b735ba175e26fe",
                       "simpl:slaAgreementsURL": "https://files.dev.simpl-europe.eu/static/pdf/SLAAgreement1.pdf"
                     },
                     "simpl:edcConnector": {
                       "simpl:providerEndpointURL": "https://edc-provider.dev.simpl-europe.eu"
                     }
                   },
                   "issuanceDate": "2024-11-13T14:56:45.099919693Z",
                   "issuer": "did:web:did.dev.simpl-europa.eu",
                   "proof": {
                     "created": "2024-11-13T14:56:45.109434764Z",
                     "jws": "eyJhbGciOiJVbmRlZmluZWQiLCJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdfQ..z-LkBu3VrEcCHO_TjdNkPsS5jQYHTwCYtKG8hUHa775zScBkIv-UgTtOjcNKzUCzRQhAN1nxXVVvah1khF1GBg",
                     "proofPurpose": "assertionMethod",
                     "type": "JsonWebSignature2020",
                     "verificationMethod": "did:web:did.dev.simpl-europa.eu#gaia-x-key1"
                   },
                   "type": "VerifiableCredential"
                 }
